# function sc() {
#   screencapture -i -x "$1.png"
# }
# function sco() {
#   screencapture -i -x "$1.png"
#   open "$1.png"
# }

#x echo "call_logs_current"
#x read var_year
#x sc call_logs_current
#x echo "call_logs_prev"
#x read var_year
#x sc call_logs_prev
#x echo "copyright_statement"
#x read var_year
#x sc copyright_statement
#x echo "data_analysis_report_template"
#x read var_year
#x sc data_analysis_report_template

# echo "data_backup_policy"
# read var_year
# sc data_backup_policy
# echo "elec_usage"
# read var_year
# sc elec_usage
# echo "email_template"
# read var_year
# sc email_template
# echo "equip_loc_guidelines"
# read var_year
# sc equip_loc_guidelines
# echo "equip_maint_schedule"
# read var_year
# sc equip_maint_schedule
# echo "fuel_usage"
# read var_year
# sc fuel_usage
# echo "hw_upgrade_req"
# read var_year
# sc hw_upgrade_req
# echo "installation_comp"
# read var_year
# sc installation_comp
# echo "instalation_plan"
# read var_year
# sc instalation_plan
# echo "internal_product_version"
# read var_year
# sc internal_product_version
# echo "it_gov_policy"
# read var_year
# sc it_gov_policy
# echo "it_infr_change_survey_results"
# read var_year
# sc it_infr_change_survey_results
# echo "it_maint_log"
# read var_year
# sc it_maint_log
# echo "it_maint_plan"
# read var_year
# sc it_maint_plan
# echo "it_maint_procedure"
# read var_year
# sc it_maint_procedure
# echo "it_procurement_policy"
# read var_year
# sc it_procurement_policy
# echo "it_whs_checklist"
# read var_year
# sc it_whs_checklist
# echo "logo"
# read var_year
# sc logo
# echo "nw_server_register - 1"
# read var_year
# sc nw_server_register1
# echo "nw_server_register - 2"
# read var_year
# sc nw_server_register2
# echo "new_staff_it_induction_kit"
# read var_year
# sc new_staff_it_induction_kit
# echo "operating_system_rollout"
# read var_year
# sc operating_system_rollout
# echo "org_chart"
# read var_year
# sc org_chart
# echo "policy_ad_eeo"
# read var_year
# sc policy_ad_eeo
# echo "policy_es"
# read var_year
# sc policy_es
# echo "policy_whs"
# read var_year
# sc policy_whs
# echo "privacy_policy"
# read var_year
# sc privacy_policy
# echo "procedure_communication"
# read var_year
# sc procedure_communication
# echo "procedure_recordsmanagement"
# read var_year
# sc procedure_recordsmanagement
# echo "procedure_start_up_shut_down"
# read var_year
# sc procedure_start_up_shut_down
# echo "procedure_use_of_ppe"
# read var_year
# sc procedure_use_of_ppe
# echo "procedure_workstation_setup"
# read var_year
# sc procedure_workstation_setup
# echo "process_recruitment"
# read var_year
# sc process_recruitment
# echo "quotation_req"
# read var_year
# sc quotation_req
# echo "report_template"
# read var_year
# sc report_template
# echo "sla"
# read var_year
# sc sla
# echo "soe"
# read var_year
# sc soe
# echo "scenario"
# read var_year
# sc scenario
# echo "scenario_add_info_1"
# read var_year
# sc scenario_add_info_1
# echo "scenario_add_info_2"
# read var_year
# sc scenario_add_info_2
# echo "scenario_add_info_3"
# read var_year
# sc scenario_add_info_3
# echo "software_test_report"
# read var_year
# sc software_test_report
# echo "strategic_plan"
# read var_year
# sc strategic_plan
# echo "style_guide"
# read var_year
# sc style_guide
# echo "task_planner"
# read var_year
# sc task_planner
# echo "user_account_policy"
# read var_year
# sc user_account_policy
# echo "user_doc_plan"
# read var_year
# sc user_doc_plan
# echo "user_eval"
# read var_year
# sc user_eval
# echo "whs_policy_draft"
# read var_year
# sc whs_policy_draft
# echo "graphics"
# read var_year
# sc graphics
